package org.vda;

public enum TaxClass 
{
	  PRIVATE_LIGHT_GOODS
	  , PETROL_CAR
	  , DIESEL_CAR
	  , ALTERNATIVE_FUEL_CAR
	  , LIGHT_GOODS_VEHICLE
	  , EURO4_LIGHT_GOODS_VEHICLE
	  , EURO5_LIGHT_GOODS_VEHICLE
	  , HEAVY_GOODS_VEHICLE
	  , PRIVATE_HEAVY_GOODS_VEHICLE
	  , SPECIAL_TYPES
	  , HAULAGE_VEHICLES
	  , BUS
	  , MOTORCYCLE
	  , ELECTRIC_MOTOCYCLE
	  , SPECIAL_VEHICLES
	  , SMALL_ISLAND_VEHICLES
	  , RECOVERY_VEHICLE
	  , SPECIAL_CONCESSIONARY
	  , EMERGENCY_VEHICLE
	  , EXCEMPT_VEHICLE

}
